### ISSUE TITLE
Update wiki - Lambda

### ISSUE THREAD

**Issue by eburdon** [eburdon/FacebookDataAnalysis#5]
New page.

Write up about how lambda was attempted, how / why it didn't work (including learning curve & error), and workaround (server stuff to trigger EMR). And also whatever else is relevant.

**Comment by ShovelHand** [comment]
Hi, crew. I wrote a wiki page for why Lambda is a jerk that made me feel bad. Please give it a quick review and close out the issue or tell me what I should change.
